version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8008:80"
    volumes:
      - ./source:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "4000:3306"
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password    
  php:
    build: .
    container_name: php
    volumes:
      - ./source:/var/www/html
    ports:
      - "9000:9000"

